SYMBOL_NAMES = [
    "EURUSD",
    "USDCHF",
    "USDJPY",
    "USDCAD",
    "AUDCHF",
    "CHFJPY",
    "EURGBP",
    "EURJPY",
    "GBPJPY",
    "BTCUSD",
    "AAL.OQ",
    "AAPL.OQ",
    "ADBE.OQ",
    "ADSGn.DE",
    "AIG.N",
    "AIRF.PA",
    "AKAM.OQ",
    "ALL.N",
    "ALVG.DE",
    "AMZN.OQ",
    "ATHM.N",
    "ATVI.OQ",
    "AXAF.PA",
    "AXP.N",
    "BA.N",
    "BABA.N",
    "BAC.N",
    "BAYGn.DE",
    "BBVA.MC",
    "BBY.N",
    "BEN.N",
    "BIDU.OQ",
    "BK.N",
    "BKNG.OQ",
    "BLK.N",
    "BMWG.DE",
    "BNPP.PA",
    "BRKb.N",
    "C.N",
    "CAPP.PA",
    "CARR.PA",
    "CBKG.DE",
    "CGC.N",
    "CMCSA.OQ",
    "COST.OQ",
    "CRM.N",
    "CRON.OQ",
    "CSCO.OQ",
    "CVS.N",
    "CVX.N",
    "DAIGn.DE",
    "DAL.N",
    "DANO.PA",
    "DBKGn.DE",
    "DBX.OQ",
    "DFS.N",
    "DIS.N",
    "DLTR.OQ",
    "DPWGn.DE",
    "DVMT.N",
    "EA.O",
    "EBAY.OQ",
    "EONGn.DE",
    "EXPE.OQ",
    "F.N",
    "FB.OQ",
    "FDX.N",
    "GDDY.N",
    "GE.N",
    "GILD.OQ",
    "GM.N",
    "GOOG.OQ",
    "GRUB.N",
    "GS.N",
    "HD.N",
    "HEIN.AS",
    "HLT.N",
    "HPQ.N",
    "HRMS.PA",
    "IBE.MC",
    "IBM.N",
    "ILMN.OQ",
    "INTC.OQ",
    "JD.OQ",
    "JNJ.N",
    "JPM.N",
    "K.N",
    "KHC.OQ",
    "KKR.N",
    "KO.N",
    "L.N",
    "LHAG.DE",
    "LK.OQ",
    "LMT.N",
    "LUV.N",
    "LVMH.PA",
    "LVS.N",
    "LYFT.OQ",
    "MA.N",
    "MAN.N",
    "MAR.OQ",
    "MCD.N",
    "MCO.N",
    "MET.N",
    "MGM.N",
    "MMM.N",
    "MO.N",
    "MOMO.OQ",
    "MRK.N",
    "MSFT.OQ",
    "MSI.N",
    "MTCH.OQ",
    "NFLX.OQ",
    "NKE.N",
    "NRG.N",
    "NTES.OQ",
    "NVDA.OQ",
    "OMC.N",
    "ORCL.N",
    "OREP.PA",
    "PDD.OQ",
    "PFE.N",
    "PG.N",
    "PINS.N",
    "PM.N",
    "PNC.N",
    "PYPL.OQ",
    "QCOM.OQ",
    "RACE.N",
    "RDSa.AS",
    "RTN.N",
    "SAN.MC",
    "SBUX.OQ",
    "SCHW.N",
    "SHOP.N",
    "SIEGn.DE",
    "SOGN.PA",
    "SQ.N",
    "T.N",
    "TEF.MC",
    "TEVA.P",
    "TGT.N",
    "TME.N",
    "TMUS.N",
    "TOTF.PA",
    "TRIP.OQ",
    "TSLA.OQ",
    "TSM.N",
    "TSN.N",
    "TWLO.N",
    "TXN.O",
    "UAL.N",
    "UBER.N",
    "V.N",
    "VIPS.N",
    "VOWG_p.DE",
    "VRSN.OQ",
    "W.N",
    "WB.N",
    "WBA.N",
    "WDAY.N",
    "WIX.OQ",
    "WMT.N",
    "WUBA.N",
    "WYNN.OQ",
    "XOM.N",
    "YELP.N",
    "YNDX.OQ",
    "YUM.N",
    "ZM.OQ",
    "ETHUSD",
    "AUDNOK",
    "AUDSEK",
    "CHFDKK",
    "CHFNOK",
    "CHFPLN",
    "CHFSGD",
    "EURHKD",
    "EURHUF",
    "EURMXN",
    "EURNOK",
    "EURNZD",
    "EURPLN",
    "EURSEK",
    "EURTRY",
    "GBPDKK",
    "GBPNOK",
    "GBPPLN",
    "GBPSEK",
    "GBPSGD",
    "GBPZAR",
    "HKDJPY",
    "MXNJPY",
    "NOKJPY",
    "NOKSEK",
    "NZDSGD",
    "SEKJPY",
    "SGDJPY",
    "TRYJPY",
    "USDCNH",
    "USDCZK",
    "USDDKK",
    "USDHUF",
    "USDMXN",
    "USDNOK",
    "USDPLN",
    "USDRUB",
    "USDSEK",
    "USDTRY",
    "USDZAR",
    "ZARJPY",
    "AUDUSD",
    "GBPUSD",
    "NZDUSD",
    "USDHKD",
    "USDSGD",
    "AUDCAD",
    "AUDJPY",
    "AUDNZD",
    "AUDSGD",
    "CADCHF",
    "CADJPY",
    "EURAUD",
    "EURCAD",
    "EURCHF",
    "EURSGD",
    "GBPAUD",
    "GBPCAD",
    "GBPCHF",
    "GBPNZD",
    "NZDCAD",
    "NZDCHF",
    "NZDJPY",
    "NGAS.f",
    "UKOIL.f",
    "USOIL.f",
    "DE30.f",
    "DJ30.f",
    "DX.f",
    "ES35.f",
    "HK50.f",
    "JP225.f",
    "SING.f",
    "SWI20.f",
    "UK100.f",
    "US500.f",
    "USTEC.f",
    "XAUUSD",
    "XRPUSD",
    "XAGUSD",
    "AUS200",
    "ESTX50",
    "FRA40",
    "GER30",
    "NAS100",
    "SPX500",
    "UK100",
    "WTI",
    "BRENT",
    "ESP35",
    "SUI20",
    "US30",
    "JPN225",
    "NE25.c",
    "JPN225.f",
    "NE25.f",
    "USCOPPER.f",
    "UKBRENT.f",
    "AIA.NZ",
    "AIR.NZ",
    "ANZ.NZ",
    "ARG.NZ",
    "ATM.NZ",
    "CEN.NZ",
    "CNU.NZ",
    "EBO.NZ",
    "FBU.NZ",
    "FNZ.NZ",
    "FPH.NZ",
    "FSF.NZ",
    "GMT.NZ",
    "GNE.NZ",
    "HGH.NZ",
    "IFT.NZ",
    "KPG.NZ",
    "MCY.NZ",
    "MEL.NZ",
    "MFT.NZ",
    "MNW.NZ",
    "NZX.NZ",
    "OCA.NZ",
    "PCT.NZ",
    "PFI.NZ",
    "POT.NZ",
    "PPH.NZ",
    "RBD.NZ",
    "RYM.NZ",
    "SKC.NZ",
    "SKL.NZ",
    "SKT.NZ",
    "SPK.NZ",
    "SUM.NZ",
    "TWR.NZ",
    "VCT.NZ",
    "VHP.NZ",
    "WBC.NZ",
    "WHS.NZ",
    "USDTHB",
    "ALGOUSD",
    "APEUSD",
    "ATOMUSD",
    "AXSUSD",
    "BTCEUR",
    "BTCGBP",
    "BTCJPY",
    "DASHUSD",
    "DOGEUSD",
    "ETHEUR",
    "ETHGBP",
    "ETHJPY",
    "FILUSD",
    "IOTAUSD",
    "LTCEUR",
    "LTCJPY",
    "NEOUSD",
    "OMGUSD",
    "QTUMUSD",
    "SOLUSD",
    "TRXUSD",
    "UNIUSD",
    "XLMUSD",
    "XMRUSD",
    "XRPJPY",
    "XTZUSD",
    "ZECUSD",
    "DE40.f",
    "CHINAA50",
    "HK50",
    "XBNB/USD",
    "XILV/USD",
    "XAX/USD",
    "XFET/USD",
    "XINJ/USD",
    "XNAKA/USD",
    "XRNDR/USD",
    "XCOTI/USD"
] 

SYMBOL_SYNONYMS = {
    # Forex
    "EURUSD": ["EUR/USD", "EURO DOLLAR", "EUROUSD", "EURUS", "EUUSD", "EURUSD=X"],
    "USDCHF": ["USD/CHF", "SWISSY", "SWISSIE", "USDCH", "USDCHF=X"],
    "USDJPY": ["USD/JPY", "DOLLAR YEN", "USDYEN", "USJPY", "USDJPY=X"],
    "USDCAD": ["USD/CAD", "LOONIE", "USDCA", "USDCAD=X"],
    "AUDCHF": ["AUD/CHF", "AUSSIE SWISS", "AUDCH", "AUDCHF=X"],
    "CHFJPY": ["CHF/JPY", "SWISS YEN", "CHFJPY=X"],
    "EURGBP": ["EUR/GBP", "EURO POUND", "EURGB", "EURGBP=X"],
    "EURJPY": ["EUR/JPY", "EURO YEN", "EURJP", "EURJPY=X"],
    "GBPJPY": ["GBP/JPY", "CABLE YEN", "GBPJP", "GBPJPY=X"],
    "AUDUSD": ["AUD/USD", "AUSSIE DOLLAR", "AUDUS", "AUDUSD=X"],
    "GBPUSD": ["GBP/USD", "CABLE", "POUND DOLLAR", "GBPUS", "GBPUSD=X"],
    "NZDUSD": ["NZD/USD", "KIWI DOLLAR", "NZDUS", "NZDUSD=X"],
    "USDHKD": ["USD/HKD", "HONG KONG DOLLAR", "USDHKD=X"],
    "USDSGD": ["USD/SGD", "SINGAPORE DOLLAR", "USDSGD=X"],
    "AUDCAD": ["AUD/CAD", "AUSSIE LOONIE", "AUDCAD=X"],
    "AUDJPY": ["AUD/JPY", "AUSSIE YEN", "AUDJPY=X"],
    "AUDNZD": ["AUD/NZD", "AUSSIE KIWI", "AUDNZD=X"],
    "AUDSGD": ["AUD/SGD", "AUSSIE SINGAPORE DOLLAR", "AUDSGD=X"],
    "CADCHF": ["CAD/CHF", "LOONIE SWISS", "CADCHF=X"],
    "CADJPY": ["CAD/JPY", "LOONIE YEN", "CADJPY=X"],
    "EURAUD": ["EUR/AUD", "EURO AUSSIE", "EURAUD=X"],
    "EURCAD": ["EUR/CAD", "EURO LOONIE", "EURCAD=X"],
    "EURCHF": ["EUR/CHF", "EURO SWISS", "EURCHF=X"],
    "EURSGD": ["EUR/SGD", "EURO SINGAPORE DOLLAR", "EURSGD=X"],
    "GBPAUD": ["GBP/AUD", "CABLE AUSSIE", "GBPAUD=X"],
    "GBPCAD": ["GBP/CAD", "CABLE LOONIE", "GBPCAD=X"],
    "GBPCHF": ["GBP/CHF", "CABLE SWISS", "GBPCHF=X"],
    "GBPNZD": ["GBP/NZD", "CABLE KIWI", "GBPNZD=X"],
    "NZDCAD": ["NZD/CAD", "KIWI LOONIE", "NZDCAD=X"],
    "NZDCHF": ["NZD/CHF", "KIWI SWISS", "NZDCHF=X"],
    "NZDJPY": ["NZD/JPY", "KIWI YEN", "NZDJPY=X"],
    "USDNOK": ["USD/NOK", "US DOLLAR NORWEGIAN KRONE", "USDNOK=X"],
    "USDSEK": ["USD/SEK", "US DOLLAR SWEDISH KRONA", "USDSEK=X"],
    "USDMXN": ["USD/MXN", "US DOLLAR MEXICAN PESO", "USDMXN=X"],
    "USDTRY": ["USD/TRY", "US DOLLAR TURKISH LIRA", "USDTRY=X"],
    "USDZAR": ["USD/ZAR", "US DOLLAR SOUTH AFRICAN RAND", "USDZAR=X"],
    "USDPLN": ["USD/PLN", "US DOLLAR POLISH ZLOTY", "USDPLN=X"],
    "USDRUB": ["USD/RUB", "US DOLLAR RUSSIAN RUBLE", "USDRUB=X"],

    # Cryptocurrencies
    "BTCUSD": ["BITCOIN", "BTC", "XBT", "BTC-USD", "BTC/USD"],
    "ETHUSD": ["ETHEREUM", "ETH", "ETH-USD", "ETH/USD"],
    "XRPUSD": ["RIPPLE", "XRP", "XRP-USD", "XRP/USD"],
    "ALGOUSD": ["ALGORAND", "ALGO", "ALGO-USD"],
    "APEUSD": ["APECOIN", "APE", "APE-USD"],
    "ATOMUSD": ["COSMOS", "ATOM", "ATOM-USD"],
    "AXSUSD": ["AXIE INFINITY", "AXS", "AXS-USD"],
    "DASHUSD": ["DASH", "DASH-USD"],
    "DOGEUSD": ["DOGECOIN", "DOGE", "DOGE-USD"],
    "FILUSD": ["FILECOIN", "FIL", "FIL-USD"],
    "IOTAUSD": ["IOTA", "IOTA-USD"],
    "NEOUSD": ["NEO", "NEO-USD"],
    "OMGUSD": ["OMG NETWORK", "OMG", "OMG-USD"],
    "QTUMUSD": ["QTUM", "QTUM-USD"],
    "SOLUSD": ["SOLANA", "SOL", "SOL-USD"],
    "TRXUSD": ["TRON", "TRX", "TRX-USD"],
    "UNIUSD": ["UNISWAP", "UNI", "UNI-USD"],
    "XLMUSD": ["STELLAR", "XLM", "XLM-USD"],
    "XMRUSD": ["MONERO", "XMR", "XMR-USD"],
    "XTZUSD": ["TEZOS", "XTZ", "XTZ-USD"],
    "ZECUSD": ["ZCASH", "ZEC", "ZEC-USD"],
    "BTCEUR": ["BTC/EUR", "BITCOIN EUR", "BTC-EUR"],
    "BTCGBP": ["BTC/GBP", "BITCOIN GBP", "BTC-GBP"],
    "BTCJPY": ["BTC/JPY", "BITCOIN JPY", "BTC-JPY"],
    "ETHEUR": ["ETH/EUR", "ETHEREUM EUR", "ETH-EUR"],
    "ETHGBP": ["ETH/GBP", "ETHEREUM GBP", "ETH-GBP"],
    "ETHJPY": ["ETH/JPY", "ETHEREUM JPY", "ETH-JPY"],
    "LTCEUR": ["LTC/EUR", "LITECOIN EUR", "LTC-EUR"],
    "LTCJPY": ["LTC/JPY", "LITECOIN JPY", "LTC-JPY"],
    "XRPJPY": ["XRP/JPY", "RIPPLE JPY", "XRP-JPY"],

    # Stocks (sample of major names, for full list just ask me)
    "AAPL.OQ": ["APPLE", "AAPL", "APPLE INC", "AAPL.OQ", "APPL"],
    "AMZN.OQ": ["AMAZON", "AMZN", "AMAZON.COM", "AMZN.OQ"],
    "MSFT.OQ": ["MICROSOFT", "MSFT", "MICROSOFT CORP", "MSFT.OQ"],
    "TSLA.OQ": ["TESLA", "TSLA", "TESLA MOTORS", "TSLA.OQ"],
    "GOOG.OQ": ["GOOGLE", "GOOG", "ALPHABET", "GOOG.OQ"],
    "FB.OQ": ["META", "FB", "FACEBOOK", "META PLATFORMS", "FB.OQ"],
    "NFLX.OQ": ["NETFLIX", "NFLX", "NFLX.OQ"],
    "AAL.OQ": ["AMERICAN AIRLINES", "AAL", "AAL.OQ"],
    "ADBE.OQ": ["ADOBE", "ADBE", "ADOBE INC", "ADBE.OQ"],
    "AKAM.OQ": ["AKAMAI TECHNOLOGIES", "AKAM", "AKAM.OQ"],
    "BABA.N": ["ALIBABA", "BABA", "BABA.N", "ALIBABA GROUP"],
    "BAC.N": ["BANK OF AMERICA", "BAC", "BAC.N"],
    "BA.N": ["BOEING", "BA", "BA.N"],
    "BK.N": ["BANK OF NEW YORK MELLON", "BK", "BK.N"],
    "C.N": ["CITIGROUP", "C", "C.N"],
    "CSCO.OQ": ["CISCO SYSTEMS", "CSCO", "CSCO.OQ"],
    "DIS.N": ["DISNEY", "DIS", "DIS.N"],
    "EBAY.OQ": ["EBAY", "EBAY", "EBAY.OQ"],
    "GE.N": ["GENERAL ELECTRIC", "GE", "GE.N"],
    "IBM.N": ["IBM", "IBM", "IBM.N"],
    "INTC.OQ": ["INTEL", "INTC", "INTC.OQ"],
    "JNJ.N": ["JOHNSON & JOHNSON", "JNJ", "JNJ.N"],
    "JPM.N": ["JPMORGAN CHASE", "JPM", "JPM.N"],
    "KO.N": ["COCA-COLA", "KO", "KO.N"],
    "LMT.N": ["LOCKHEED MARTIN", "LMT", "LMT.N"],
    "MCD.N": ["MCDONALD'S", "MCD", "MCD.N"],
    "MET.N": ["METLIFE", "MET", "MET.N"],
    "MMM.N": ["3M COMPANY", "MMM", "MMM.N"],
    "NKE.N": ["NIKE", "NKE", "NKE.N"],
    "PFE.N": ["PFIZER", "PFE", "PFE.N"],
    "PG.N": ["PROCTER & GAMBLE", "PG", "PG.N"],
    "PYPL.OQ": ["PAYPAL", "PYPL", "PYPL.OQ"],
    "QCOM.OQ": ["QUALCOMM", "QCOM", "QCOM.OQ"],
    "SBUX.OQ": ["STARBUCKS", "SBUX", "SBUX.OQ"],
    "T.N": ["AT&T", "T", "T.N"],
    "TSM.N": ["TSMC", "TSM", "TSM.N"],
    "UAL.N": ["UNITED AIRLINES", "UAL", "UAL.N"],
    "V.N": ["VISA", "V", "V.N"],
    "WMT.N": ["WALMART", "WMT", "WMT.N"],
    "XOM.N": ["EXXON MOBIL", "XOM", "XOM.N"],

    # Indices (some examples)
    "DJ30.f": ["DOW JONES", "DJIA", "DOW", "US30", "DJI", "YM", "DJ30.F"],
    "GER30": ["DAX", "DAX30", "DE30.F", "DAX30.F", "GER30.F"],
    "NAS100": ["NASDAQ 100", "NASDAQ100", "US100", "NDX", "NASDAQ", "NQ"],
    "SPX500": ["S&P 500", "SP500", "SPX", "ES", "ES1!", "US500", "SPY"],
    "UK100": ["FTSE 100", "FTSE100", "UKX", "UK100.F"],

    # Commodities
    "WTI": ["CRUDE OIL", "WTI OIL", "CL", "CL1!", "LIGHT SWEET CRUDE", "USOIL", "USOIL.F"],
    "BRENT": ["BRENT OIL", "UKOIL", "BRN", "BZ", "BRN1!", "UKBRENT.F"],
    "NGAS.f": ["NATURAL GAS", "NG", "GAS", "NAT GAS", "NGAS"],
    "XAUUSD": ["GOLD", "XAU", "GOUD", "GOLD SPOT", "GOLD/USD"],
    "XAGUSD": ["SILVER", "XAG", "SILVER", "SILVER SPOT", "SILVER/USD"],
}
